### ISSUE TITLE
!woof command html parsing fails

### ISSUE THREAD

**Issue by cmxl** [Woofie-Woof/Yoshi-Bot#4]
When parsing the src attribute of the random.dog page you try to substring until you find a single quote `'`, but the attribute terminates with a double quote `"`. So no image will be shown in discord, but only the link to the main page.

EDIT:
Also there is an endpoint called [https://random.dog/woof](https://random.dog/woof) wich returns a random picture name as plain text. Seems to be a better way to create the image url without parsing with a magic length.

**Comment by Woofie-Woof** [comment]
Lol, the whole random.dog parsing I did because I had no idea if an actual random end point existed. That trickery seemed to work the best. I'll fix it up, thanks a lot for pointing out both the error and the end point.
